default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cabin_development

production:
  <<: *default
  database: cabin_production

test:
  <<: *sqlite
  database: db/test.sqlite3
